version: '3.7'

services:
  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/ 
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    volumes:
      - ".blob:/data"
